Error: CLX-673 moved Error-Component from core to core_modules
(cherry picked from commit 14b6a1537de46511d205b8172cdd3da2335ad1d9)

Conflicts:
	core_modules/Error/Controller/ComponentController.class.php
	core_modules/Error/Controller/Error.class.php
	core_modules/Error/Model/Entity/ShinyException.class.php