Error: CLX-673 adapted the installer/data/contrexx_dump_data.sql-file to only contain the changeset of moving the error-component
(cherry picked from commit 179bf3ae4f5eefd3da3ca81296df15f16c963ed9)

Conflicts:
	installer/data/contrexx_dump_data.sql