Error: CLX-673 moved contrexx_dumps from root to their proper locations in installe/data/
(cherry picked from commit 620ad809e9819914f3437c0dde9debc36e66fab2)

Conflicts:
	installer/data/contrexx_dump_data.sql
	installer/data/contrexx_dump_structure.sql